# Generated by Django 5.0.2 on 2025-04-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
