# Generated by Django 5.0.2 on 2025-04-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_customfield_is_required'),
    ]

    operations = [
    ]
